//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bans")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub intruder: String,
    #[sea_orm(column_type = "Text")]
    pub admin: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub round_id: i32,
    #[sea_orm(column_type = "Text")]
    pub server: String,
    pub duration_end: DateTime,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
